global using Energetic.NET.ASPNETCore;
global using Energetic.NET.ASPNETCore.Attributes;
global using Microsoft.AspNetCore.Mvc;
global using Energetic.NET.Infrastructure;
global using Energetic.NET.SharedKernel;
global using Energetic.NET.Basic.Domain.Models;
global using Energetic.NET.Basic.Infrastructure;
global using EasyCaching.Core;
global using MapsterMapper;
